#! /bin/sh

# Source colours and icons
. panel_config

# Set the icon when no music is playing
icoMUSIQUE="%{F$BASE02}%{B$CYAN} $icoMUSIC %{F-}%{B$BASE02}"

while :; do
    sleep 0.5
    # Is mopidy running?
    if  pidof -x mopidy && mpc status; then
        cur=`mpc current`


        # Check if a song is [playing, paused, else]
        # and set the corrent icon, color and message
        if mpc status | grep -oe playing ; then
            echo "c%{F$BASE02}%{B$GREEN} $icoPLAY %{F-}%{B$BASE02} $cur"
        elif mpc status | grep -oe paused ; then
            echo "c%{F$BASE02}%{B$CYAN} $icoPAUSE %{F-}%{B$BASE02} $cur"
        else
            echo "c$icoMUSIQUE - stopped -"
        fi

        # Wait for next player command
        mpc idle player

    else
        echo "c$icoMUSIQUE - Mopidy not running - "
    fi
done
