#! /bin/sh
PANEL_FONT_FAMILY=""*-stlarch-medium-r-normal--10*","-*-terminesspowerline-medium-r-normal-*-12-*-*-*-c-*-*-1""


BASE03=#ff002b36
BASE02=#ff073642
BASE01=#ff586e75
BASE00=#ff657b83
BASE0=#ff839496
BASE1=#ff93a1a1
BASE2=#ffeee8d5
BASE3=#fffdf6e3


YELLOW=#ffb58900
ORANGE=#ffcb4b16
RED=#ffdc322f
MAGENTA=#ffd33682
VIOLET=#ff6c71c4
BLUE=#ff268bd2
CYAN=#ff2aa198
GREEN=#ff859900

COLOR_FOREGROUND=$BASE1
COLOR_BACKGROUND=$BASE03

icoARCH=""
icoPACMAN=""
icoUPTIME=""

icoFREE=""
icoOCC=""

icoPLAY=""
icoPAUSE=""
icoMUSIC=""

icoVOL0=""
icoVOL=""
icoMUTE=""

icoTIME=""
icoCONN=""
icoDISCO=""

icoSTORAGE=""
icoCPU=""
icoRAM=""

