#! /bin/sh

# Screen Padding
bspc config top_padding 36
bspc config left_padding 12
bspc config right_padding 12
bspc config bottom_padding 40

bspc config border_width 0
bspc config window_gap 16
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_by_distance true
bspc config adaptive_raise true
bspc config auto_cancel true
bspc config normal_frame_opacity 0.01
bspc config focused_frame_opacity 1.00

# bscp config focused_border_color "#8f8f8f"
# bscp config normal_border_color "#1c1c1c"
# bscp config active_border_color "#8f8f8f"
# bscp config presel_border_color "#7e8e91"
# bscp config urgent_border_color "#7e8e91"


bspc monitor DVI-I-1 -d 1 2 3
bspc monitor VGA-1 -d 4 5 6
bspc rule -a Firefox desktop=^1
bspc rule -a mupdf window=pseudo_tiled
bspc rule -a Gimp desktop=^4 follow=on floating=on

compton --config ~/.config/compton/compton.conf &
sleep 2
panel &

